In [1]:
import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt('training.txt')
data

array([[19.410541 , 11.45899  ,  0.       ],
       [23.765585 , 13.972661 ,  0.       ],
       [10.719978 ,  8.8566508,  0.       ],
       ...,
       [ 8.8913669, 12.265898 ,  1.       ],
       [14.197481 , 10.280842 ,  1.       ],
       [ 6.7481281, 10.253769 ,  1.       ]])

In [2]:
val_data = np.loadtxt('test.txt')
val_data

array([[17.152491 ,  7.6907257,  0.       ],
       [15.226864 , 11.814989 ,  0.       ],
       [19.568989 , 13.543812 ,  0.       ],
       ...,
       [ 7.2258284,  9.3664595,  1.       ],
       [10.041861 ,  8.8377143,  1.       ],
       [10.046262 ,  8.3111921,  1.       ]])

In [3]:
def suffle(x):
    arr = np.arange(0, len(x))
    np.random.shuffle(arr)
    return x[arr]   

In [4]:
suffled_data = suffle(data)
suffled_data

array([[15.267993 ,  4.3789998,  0.       ],
       [17.38346  , 10.709627 ,  0.       ],
       [16.68298  , 14.671074 ,  0.       ],
       ...,
       [ 8.6752392,  9.4874963,  1.       ],
       [10.773205 , 11.957868 ,  1.       ],
       [ 9.8161219, 11.292079 ,  1.       ]])

In [5]:
suffled_val_data = suffle(val_data)
suffled_val_data

array([[14.678536 ,  6.4424337,  0.       ],
       [14.761009 ,  7.7152568,  0.       ],
       [20.172687 ,  9.3799797,  0.       ],
       ...,
       [ 5.244725 ,  9.8328014,  1.       ],
       [ 5.0250538,  9.7395243,  1.       ],
       [18.866421 ,  6.5913827,  0.       ]])

In [6]:
splited_data = np.split(suffled_data, (2, 3), axis=1)
X = splited_data[0]
y = splited_data[1]
print(X)
print(y)

[[15.267993   4.3789998]
 [17.38346   10.709627 ]
 [16.68298   14.671074 ]
 ...
 [ 8.6752392  9.4874963]
 [10.773205  11.957868 ]
 [ 9.8161219 11.292079 ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

In [7]:
splited_val_data = np.split(suffled_val_data, (2, 3), axis=1)
X_val = splited_val_data[0]
y_val = splited_val_data[1]
print(X_val)
print(y_val)

[[14.678536   6.4424337]
 [14.761009   7.7152568]
 [20.172687   9.3799797]
 ...
 [ 5.244725   9.8328014]
 [ 5.0250538  9.7395243]
 [18.866421   6.5913827]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [0.]]


In [8]:
X.shape[0]

1000

In [9]:
X_val.shape[0]

3000

In [10]:
from layer import BasicNeuralNetwork

in_dim_n = 2 
hidden_dim_n = 8 
out_dim_n = 1
epoch = 100
learning_rate = 0.01
batch_size = 1
clip_grad_l2 = 1
optim_fn = 'sgd'

bnn = BasicNeuralNetwork(
    in_dim_n, hidden_dim_n, out_dim_n, epoch, learning_rate, batch_size, optim_fn, clip_grad_l2)

In [11]:
result, val_result = bnn.train(X, y, X_val, y_val)
plt.plot(result)
plt.plot(val_result)

TypeError: cannot pickle 'generator' object

In [ ]:
val_result

In [ ]:
result

In [ ]:
len(result)

In [ ]:
val_result

In [ ]:
batch_size = 10

bnn = BasicNeuralNetwork(
    in_dim_n, hidden_dim_n, out_dim_n, epoch, learning_rate, batch_size, optim_fn, clip_grad_l2)

result = bnn.train(X, y)
plt.plot(result)

In [ ]:
batch_size = 100

bnn = BasicNeuralNetwork(
    in_dim_n, hidden_dim_n, out_dim_n, epoch, learning_rate, batch_size, optim_fn, clip_grad_l2)

result = bnn.train(X, y)
plt.plot(result)