In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = np.loadtxt('training.txt')
data

array([[19.410541 , 11.45899  ,  0.       ],
       [23.765585 , 13.972661 ,  0.       ],
       [10.719978 ,  8.8566508,  0.       ],
       ...,
       [ 8.8913669, 12.265898 ,  1.       ],
       [14.197481 , 10.280842 ,  1.       ],
       [ 6.7481281, 10.253769 ,  1.       ]])

In [2]:
def suffle(x):
    arr = np.arange(0, len(x))
    np.random.shuffle(arr)
    return x[arr]   

In [3]:
suffled_data = suffle(data)
suffled_data

array([[19.571285 , 13.381685 ,  0.       ],
       [19.772844 ,  6.0640428,  0.       ],
       [ 8.410749 , 10.136136 ,  1.       ],
       ...,
       [12.051464 ,  6.5346955,  0.       ],
       [18.515463 ,  8.3580297,  0.       ],
       [17.203107 ,  8.7029621,  0.       ]])

In [4]:
splited_data = np.split(suffled_data, (2, 3), axis=1)
X = splited_data[0]
y = splited_data[1]
X

array([[19.571285 , 13.381685 ],
       [19.772844 ,  6.0640428],
       [ 8.410749 , 10.136136 ],
       ...,
       [12.051464 ,  6.5346955],
       [18.515463 ,  8.3580297],
       [17.203107 ,  8.7029621]])

In [5]:
y

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],

In [6]:
# TODO batchsize=1, stochastic gradient

In [7]:
from layer import BasicNeuralNetwork

in_dim_n = 2 
hidden_dim_n = 8 
out_dim_n = 1
epoch = 1000
learning_rate = 0.01

bnn = BasicNeuralNetwork(in_dim_n,
                         hidden_dim_n,
                         out_dim_n,
                         epoch,
                         learning_rate)

In [8]:
result = bnn.train(X, y)
plt.plot(result)

Epoch: 1000, Iteration: 0, Loss: 0.8611427567777777
[2.55603308] [0.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 8)