In [1]:
import torch
from torch import nn

In [2]:
import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt('training.txt')
data

array([[19.410541 , 11.45899  ,  0.       ],
       [23.765585 , 13.972661 ,  0.       ],
       [10.719978 ,  8.8566508,  0.       ],
       ...,
       [ 8.8913669, 12.265898 ,  1.       ],
       [14.197481 , 10.280842 ,  1.       ],
       [ 6.7481281, 10.253769 ,  1.       ]])

In [3]:
val_data = np.loadtxt('test.txt')
val_data

array([[17.152491 ,  7.6907257,  0.       ],
       [15.226864 , 11.814989 ,  0.       ],
       [19.568989 , 13.543812 ,  0.       ],
       ...,
       [ 7.2258284,  9.3664595,  1.       ],
       [10.041861 ,  8.8377143,  1.       ],
       [10.046262 ,  8.3111921,  1.       ]])

In [4]:
def suffle(x):
    arr = np.arange(0, len(x))
    np.random.shuffle(arr)
    return x[arr]

In [5]:
suffled_data = suffle(data)
suffled_data

array([[ 5.1542709,  5.6499351,  1.       ],
       [ 6.7741006, 10.276187 ,  1.       ],
       [21.890638 , 14.712958 ,  0.       ],
       ...,
       [ 8.4132093,  9.4021859,  1.       ],
       [12.19873  , 10.47455  ,  1.       ],
       [10.374417 ,  2.9909107,  0.       ]])

In [6]:
suffled_val_data = suffle(val_data)
suffled_val_data

array([[18.536494 , 12.763616 ,  0.       ],
       [ 9.1889178,  9.2133948,  1.       ],
       [20.401484 , 10.394007 ,  0.       ],
       ...,
       [15.02272  , 10.400011 ,  0.       ],
       [10.698211 , 10.465865 ,  1.       ],
       [10.99268  ,  8.2932453,  1.       ]])

In [7]:
splited_data = np.split(suffled_data, (2, 3), axis=1)
X = splited_data[0]
y = splited_data[1]
print(X)
print(y)

[[ 5.1542709  5.6499351]
 [ 6.7741006 10.276187 ]
 [21.890638  14.712958 ]
 ...
 [ 8.4132093  9.4021859]
 [12.19873   10.47455  ]
 [10.374417   2.9909107]]
[[1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.

In [8]:
splited_val_data = np.split(suffled_val_data, (2, 3), axis=1)
X_val = splited_val_data[0]
y_val = splited_val_data[1]
print(X_val)
print(y_val)

[[18.536494  12.763616 ]
 [ 9.1889178  9.2133948]
 [20.401484  10.394007 ]
 ...
 [15.02272   10.400011 ]
 [10.698211  10.465865 ]
 [10.99268    8.2932453]]
[[0.]
 [1.]
 [0.]
 ...
 [0.]
 [1.]
 [1.]]


In [9]:
X.shape[0]

1000

In [10]:
X_val.shape[0]

3000

In [11]:
X_tensor = torch.Tensor(X)
y_tensor = torch.Tensor(y)
X_val_tensor = torch.Tensor(X_val)
y_val_tensor = torch.Tensor(y_val)

In [12]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_stack = nn.Sequential(
            nn.Linear(2, 8),
            nn.BatchNorm1d(1, 8),
            nn.Sigmoid(),
            nn.Linear(8, 1),
            nn.BatchNorm1d(2),
            nn.Sigmoid(),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_stack(x)
        return logits

In [13]:
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_stack): Sequential(
    (0): Linear(in_features=2, out_features=8, bias=True)
    (1): BatchNorm1d(1, eps=8, momentum=0.1, affine=True, track_running_stats=True)
    (2): Sigmoid()
    (3): Linear(in_features=8, out_features=1, bias=True)
    (4): BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): Sigmoid()
  )
)


In [14]:
def train_loop(model, loss_fn, optimizer, X, y):
    batch_mask = torch.randint(0, 1000, (1, ))

    # Compute prediction and loss
    pred = model(X[batch_mask])
    loss = loss_fn(pred, y[batch_mask])

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    loss= loss.item()
    print(f"loss: {loss:>7f}")
    return loss


# def test_loop(model, loss_fn):
#     num_batches = len(dataloader)
#     test_loss, correct = 0, 0
#
#     with torch.no_grad():
#         for X, y in dataloader:
#             pred = model(X)
#             test_loss += loss_fn(pred, y).item()
#             correct += (pred.argmax(1) == y).type(torch.float).sum().item()
#
#     test_loss /= num_batches
#     correct /= size
#     print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [15]:
learning_rate = 1e-2
epochs = 10000

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

results = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    result = train_loop(model, loss_fn, optimizer, X_tensor, y_tensor)
    results.append(result)
    # test_loop(test_dataloader, model, loss_fn)
print("Done!")

plt.plot(results)

Epoch 1
-------------------------------


ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 8])

In [ ]:
model = NeuralNetwork()

optimizer = torch.optim.Adagrad(model.parameters(), lr=learning_rate)

results = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    result = train_loop(model, loss_fn, optimizer, X_tensor, y_tensor)
    results.append(result)
    # test_loop(test_dataloader, model, loss_fn)
print("Done!")

plt.plot(results)